In [3]:
baduta_path = "E:\Coolyeah\Other\Compfest\Analysis\datasets\\baduta.csv"
hdi_path = "E:\Coolyeah\Other\Compfest\Analysis\datasets\hdi_nasional.csv"
life_expectancy_path = "E:\Coolyeah\Other\Compfest\Analysis\datasets\life_expectancy_nasional.csv"
stunting_path = "E:\Coolyeah\Other\Compfest\Analysis\datasets\Prev Stunting Nasional 2019-2024.csv"

In [5]:
import pandas as pd
import numpy as np

baduta = pd.read_csv(baduta_path)
hdi = pd.read_csv(hdi_path)
life_expectancy = pd.read_csv(life_expectancy_path)
stunting = pd.read_csv(stunting_path, delimiter = ";")

In [6]:
baduta

   Tahun  PrevalensiBaduta
0   2020              10.4
1   2021               9.2
2   2022               7.4
3   2023               7.7
4   2024               6.5

In [7]:
hdi

    Tahun    HDI
0    2013  68.31
1    2014  68.90
2    2015  69.55
3    2016  70.18
4    2017  70.81
5    2018  71.39
6    2019  71.92
7    2020  71.94
8    2021  72.29
9    2022  72.91
10   2023  73.55
11   2024  74.20

In [8]:
life_expectancy

    Tahun  Life Expectancy at Birth (Year)
0    2013                            70.40
1    2014                            70.59
2    2015                            70.78
3    2016                            70.90
4    2017                            71.06
5    2018                            71.20
6    2019                            71.34
7    2020                            71.47
8    2021                            71.57
9    2022                            71.85
10   2023                            72.13
11   2024                            72.39

In [9]:
stunting

    tahun prevalensi                                     source
0    2013       37,2                             Riskesdas 2013
1    2014       37,0  Setneg (Pernyataan Presiden RI, Jan 2023)
2    2015       29,0             PSG 2015 (Kemenkes/Berkas DPR)
3    2016       27,5             PSG 2016 (Kemenkes/Berkas DPR)
4    2017       29,6             PSG 2017 (Kemenkes/Berkas DPR)
5    2018       30,8                             Riskesdas 2018
6    2019       27,7                         SSGBI+Susenas 2019
7    2020      26,92                  Prediksi Litbangkes & BPS
8    2021       24,4                                  SSGI 2021
9    2022       21,6                                  SSGI 2022
10   2023       21,5                              SKI/SSGI 2023
11   2024       19,8                                  SSGI 2024

In [11]:
# replace comma in stunting with .
stunting["prevalensi"] = stunting["prevalensi"].astype(str).str.replace(",", ".").astype(float)

In [15]:
stunting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tahun       12 non-null     int64
 1   prevalensi  12 non-null     float64
 2   source      12 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 420.0+ bytes

In [20]:
# combine
df = hdi.merge(baduta, on="Tahun", how="outer")

In [22]:
df = df.merge(life_expectancy, on="Tahun", how="outer")
df

    Tahun    HDI  PrevalensiBaduta  Life Expectancy at Birth (Year)
0    2013  68.31               NaN                            70.40
1    2014  68.90               NaN                            70.59
2    2015  69.55               NaN                            70.78
3    2016  70.18               NaN                            70.90
4    2017  70.81               NaN                            71.06
5    2018  71.39               NaN                            71.20
6    2019  71.92               NaN                            71.34
7    2020  71.94              10.4                            71.47
8    2021  72.29               9.2                            71.57
9    2022  72.91               7.4                            71.85
10   2023  73.55               7.7                            72.13
11   2024  74.20               6.5                            72.39

In [24]:
stunting['Tahun'] = stunting['tahun']
stunting.drop(['tahun'], axis=1, inplace=True)

In [25]:
stunting

    prevalensi                                     source  Tahun
0        37.20                             Riskesdas 2013   2013
1        37.00  Setneg (Pernyataan Presiden RI, Jan 2023)   2014
2        29.00             PSG 2015 (Kemenkes/Berkas DPR)   2015
3        27.50             PSG 2016 (Kemenkes/Berkas DPR)   2016
4        29.60             PSG 2017 (Kemenkes/Berkas DPR)   2017
5        30.80                             Riskesdas 2018   2018
6        27.70                         SSGBI+Susenas 2019   2019
7        26.92                  Prediksi Litbangkes & BPS   2020
8        24.40                                  SSGI 2021   2021
9        21.60                                  SSGI 2022   2022
10       21.50                              SKI/SSGI 2023   2023
11       19.80                                  SSGI 2024   2024

In [26]:
df = df.merge(stunting, on="Tahun", how="outer")
df

,Tahun,HDI,PrevalensiBaduta,Life Expectancy at Birth (Year),prevalensi,source
0,2013,68.31,NaN,70.40,37.20,Riskesdas 2013
1,2014,68.90,NaN,70.59,37.00,"Setneg (Pernyataan Presiden RI, Jan 2023)"
2,2015,69.55,NaN,70.78,29.00,PSG 2015 (Kemenkes/Berkas DPR)
3,2016,70.18,NaN,70.90,27.50,PSG 2016 (Kemenkes/Berkas DPR)
4,2017,70.81,NaN,71.06,29.60,PSG 2017 (Kemenkes/Berkas DPR)
5,2018,71.39,NaN,71.20,30.80,Riskesdas 2018
6,2019,71.92,NaN,71.34,27.70,SSGBI+Susenas 2019
7,2020,71.94,10.4,71.47,26.92,Prediksi Litbangkes & BPS
8,2021,72.29,9.2,71.57,24.40,SSGI 2021
9,2022,72.91,7.4,71.85,21.60,SSGI 2022
10,2023,73.55,7.7,72.13,21.50,SKI/SSGI 2023
11,2024,74.20,6.5,72.39,19.80,SSGI 2024

In [30]:
df_filtered = df[(df["Tahun"] >= 2020) & (df["Tahun"] <= 2024)]

In [ ]:
df_filtered

,Tahun,HDI,PrevalensiBaduta,Life Expectancy at Birth (Year),prevalensi,source
7,2020,71.94,10.4,71.47,26.92,Prediksi Litbangkes & BPS
8,2021,72.29,9.2,71.57,24.40,SSGI 2021
9,2022,72.91,7.4,71.85,21.60,SSGI 2022
10,2023,73.55,7.7,72.13,21.50,SKI/SSGI 2023
11,2024,74.20,6.5,72.39,19.80,SSGI 2024

In [ ]:
df_filtered.drop(['source'], axis=1, inplace=True)
df_filtered

D:\pip_temp\ipykernel_34284\661975774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.drop(['source'], axis=1, inplace=True)

,Tahun,HDI,PrevalensiBaduta,Life Expectancy at Birth (Year),prevalensi
7,2020,71.94,10.4,71.47,26.92
8,2021,72.29,9.2,71.57,24.40
9,2022,72.91,7.4,71.85,21.60
10,2023,73.55,7.7,72.13,21.50
11,2024,74.20,6.5,72.39,19.80

In [89]:
numeric_df = df_filtered.select_dtypes(include="number")
numeric_df.rename(columns={'PrevalensiBaduta':'Stunting Baduta', 'Life Expectancy at Birth (Year)': 'Life Expectancy', 'prevalensi': 'Stunting Balita'}, inplace=True)

In [90]:
numeric_df.drop(['Tahun'], axis=1, inplace=True)

In [ ]:

corr = numeric_df.corr()

plt.figure(figsize=(10, 8))

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f",
            xticklabels=corr.columns, yticklabels=corr.columns)

plt.title("Correlation Matrix Heatmap 2020-2024", fontsize=14)

plt.xticks(rotation=0)
plt.yticks(rotation=0)

plt.tight_layout()

plt.savefig("correlation_matrix_hd.png", dpi=300, bbox_inches="tight")
plt.close()

In [ ]:
plt.savefig("correlation_matrix.png", dpi=300) 
plt.close()

In [ ]:
df_filtered.to_csv("combined_data.csv", index=False)

In [73]:
df_all_path = ("combined_data.csv")
df_all = pd.read_csv(df_all_path)
df_all

,Tahun,HDI,Prevalensi Baduta,Life Expectancy,Prevalensi Balita,Gini,Harapan Tahun Sekolah
0,2020,71.94,10.4,71.47,26.92,0.381,12.98
1,2021,72.29,9.2,71.57,24.40,0.384,13.08
2,2022,72.91,7.4,71.85,21.60,0.384,13.10
3,2023,73.55,7.7,72.13,21.50,0.388,13.15
4,2024,74.20,6.5,72.39,19.80,0.379,13.21

In [74]:
numeric_df = df_all.select_dtypes(include="number")

In [66]:
numeric_df

,Tahun,HDI,Prevalensi Baduta,Life Expectancy,Prevalensi Balita,Gini,Harapan Tahun Sekolah
0,2020,71.94,10.4,71.47,26.92,0.381,12.98
1,2021,72.29,9.2,71.57,24.40,0.384,13.08
2,2022,72.91,7.4,71.85,21.60,0.384,13.10
3,2023,73.55,7.7,72.13,21.50,0.388,13.15
4,2024,74.20,6.5,72.39,19.80,0.379,13.21

In [ ]:
corr = numeric_df.corr()

plt.figure(figsize=(15, 8))

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f",
            xticklabels=corr.columns, yticklabels=corr.columns)

plt.title("Correlation Matrix Heatmap 2020-2024", fontsize=25)

plt.xticks(rotation=0, fontsize=12)
plt.yticks(rotation=0, fontsize=12)
plt.tight_layout()

plt.savefig("corr_matrix.png", dpi=300, bbox_inches="tight")
plt.close()